 services: 
  worker_host:
    build:
      context: ../..
      dockerfile: server/worker_host/Dockerfile
    image: halloween/worker_host:latest
    container_name: halloween_worker_host
    restart: unless-stopped
    depends_on:
      - mqtt
    env_file:
      - ../../config/secrets/mqtt_users.env
      - ../../config/secrets/tesla.env
      - ../../config/worker_host.env
    environment:
      - PYTHONPATH=/app:/opt/libs/py:/opt/builtin_workers
    volumes:
      - ../../props:/app/props:ro
      - ../../libs/py:/opt/libs/py:ro
    labels:
      com.halloween.role: "worker_host"      

  media_server:
    image: nginx:1.25-alpine
    container_name: halloween_media_server
    restart: unless-stopped
    volumes:
      # Mount the top-level media folder into the Nginx web root
      - ../../media:/usr/share/nginx/html:ro
    ports:
      # Expose port 8000 on the host, mapping to port 80 in the container
      - "8000:80"
