 services: 
  worker_host:
    build:
      context: ../..
      dockerfile: server/worker_host/Dockerfile
    image: halloween/worker_host:latest
    container_name: halloween_worker_host
    restart: unless-stopped
    depends_on:
      - mqtt
    env_file:
      - ../../config/secrets/mqtt_users.env
      - ../../config/secrets/tesla.env
      - ../../config/worker_host.env
    environment:
      - PYTHONPATH=/app:/opt/libs/py:/opt/builtin_workers
    volumes:
      - ../../props:/app/props:ro
      - ../../libs/py:/opt/libs/py:ro
    labels:
      com.halloween.role: "worker_host"      